WebTemplateTest/WebTemplateTest/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebTemplateTest.Controllers
{
    public class IndexController : Controller
    {
        // GET: Index
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Codes()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult ShanonFano()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult Hufman()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult LinearCodes()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult SystematicForm()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult SystematicallyDecoding()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult Hemming()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult Meggitt()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult ReedMuller()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult HemmingTheory()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult HufmanTheory()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult LinearCodesTheory()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult MeggittTheory()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult ReedMullerTheory()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult ShanonFanoTheory()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult SystematicallyDecodingTheory()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult SystematicFormTheory()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult HemmingExample()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult HufmanExample()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult LinearCodesExample()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult MeggittExample()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult ReedMullerExample()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult ShanonFanoExample()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult SystematicallyDecodingExample()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult SystematicFormExample()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult Questions()
        {
            return PartialView();
        }
    }
}

WebTemplateTest/WebTemplateTest/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<!--
 * A Design by GraphBerry
 * Author: GraphBerry
 * Author URL: http://graphberry.com
 * License: http://graphberry.com/pages/license
-->
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moredno Html theme by GraphBerry.com</title>

    <!-- Load fonts -->
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>

    <!-- Load css styles -->
    <link rel="stylesheet" type="text/css" href="../Content/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="../Content/font-awesome.css" />
    <link rel="stylesheet" type="text/css" href="../Content/style.css" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>